export class ProgramChange {
    readonly value: number;
    readonly instrument: string;
    readonly type: string;
    readonly percussionValue: number | null = null;
    readonly percussionNote: string | null = null;

    constructor(value: number, instrument: string, type: string, percussionValue: number | null = null, percussionNote: string | null = null) {
        this.value = value;
        this.instrument = instrument;
        this.type = type;
        this.percussionValue = percussionValue;
        this.percussionNote = percussionNote;
    }
}

export class ProgramChanges {
    static readonly programChanges: ProgramChange[] = [
        new ProgramChange(0, "Acoustic grand piano", "Piano"),
        new ProgramChange(1, "Bright acoustic piano", "Piano"),
        new ProgramChange(2, "Electric grand piano", "Piano"),
        new ProgramChange(3, "Honky tonk piano", "Piano"),
        new ProgramChange(4, "Electric piano 1", "Piano"),
        new ProgramChange(5, "Electric piano 2", "Piano"),
        new ProgramChange(6, "Harpsicord", "Piano"),
        new ProgramChange(7, "Clavinet", "Piano"),
        new ProgramChange(8, "Celesta", "Chromatic percussion"),
        new ProgramChange(9, "Glockenspiel", "Chromatic percussion"),
        new ProgramChange(10, "Music box", "Chromatic percussion"),
        new ProgramChange(11, "Vibraphone", "Chromatic percussion"),
        new ProgramChange(12, "Marimba", "Chromatic percussion"),
        new ProgramChange(13, "Xylophone", "Chromatic percussion"),
        new ProgramChange(14, "Tubular bell", "Chromatic percussion"),
        new ProgramChange(15, "Dulcimer", "Chromatic percussion"),
        new ProgramChange(16, "Hammond / drawbar organ", "Organ"),
        new ProgramChange(17, "Percussive organ", "Organ"),
        new ProgramChange(18, "Rock organ", "Organ"),
        new ProgramChange(19, "Church organ", "Organ"),
        new ProgramChange(20, "Reed organ", "Organ"),
        new ProgramChange(21, "Accordion", "Organ"),
        new ProgramChange(22, "Harmonica", "Organ"),
        new ProgramChange(23, "Tango accordion", "Organ"),
        new ProgramChange(24, "Nylon string acoustic guitar", "Guitar"),
        new ProgramChange(25, "Steel string acoustic guitar", "Guitar"),
        new ProgramChange(26, "Jazz electric guitar", "Guitar"),
        new ProgramChange(27, "Clean electric guitar", "Guitar"),
        new ProgramChange(28, "Muted electric guitar", "Guitar"),
        new ProgramChange(29, "Overdriven guitar", "Guitar"),
        new ProgramChange(30, "Distortion guitar", "Guitar"),
        new ProgramChange(31, "Guitar harmonics", "Guitar"),
        new ProgramChange(32, "Acoustic bass", "Bass"),
        new ProgramChange(33, "Fingered electric bass", "Bass"),
        new ProgramChange(34, "Picked electric bass", "Bass"),
        new ProgramChange(35, "Fretless bass", "Bass"),
        new ProgramChange(36, "Slap bass 1", "Bass"),
        new ProgramChange(37, "Slap bass 2", "Bass"),
        new ProgramChange(38, "Synth bass 1", "Bass"),
        new ProgramChange(39, "Synth bass 2", "Bass"),
        new ProgramChange(40, "Violin", "Strings"),
        new ProgramChange(41, "Viola", "Strings"),
        new ProgramChange(42, "Cello", "Strings"),
        new ProgramChange(43, "Contrabass", "Strings"),
        new ProgramChange(44, "Tremolo strings", "Strings"),
        new ProgramChange(45, "Pizzicato strings", "Strings"),
        new ProgramChange(46, "Orchestral strings / harp", "Strings"),
        new ProgramChange(47, "Timpani", "Strings"),
        new ProgramChange(48, "String ensemble 1", "Ensemble"),
        new ProgramChange(49, "String ensemble 2 / slow strings", "Ensemble"),
        new ProgramChange(50, "Synth strings 1", "Ensemble"),
        new ProgramChange(51, "Synth strings 2", "Ensemble"),
        new ProgramChange(52, "Choir aahs", "Ensemble"),
        new ProgramChange(53, "Voice oohs", "Ensemble"),
        new ProgramChange(54, "Synth choir / voice", "Ensemble"),
        new ProgramChange(55, "Orchestra hit", "Ensemble"),
        new ProgramChange(56, "Trumpet", "Brass"),
        new ProgramChange(57, "Trombone", "Brass"),
        new ProgramChange(58, "Tuba", "Brass"),
        new ProgramChange(59, "Muted trumpet", "Brass"),
        new ProgramChange(60, "French horn", "Brass"),
        new ProgramChange(61, "Brass ensemble", "Brass"),
        new ProgramChange(62, "Synth brass 1", "Brass"),
        new ProgramChange(63, "Synth brass 2", "Brass"),
        new ProgramChange(64, "Soprano sax", "Reed"),
        new ProgramChange(65, "Alto sax", "Reed"),
        new ProgramChange(66, "Tenor sax", "Reed"),
        new ProgramChange(67, "Baritone sax", "Reed"),
        new ProgramChange(68, "Oboe", "Reed"),
        new ProgramChange(69, "English horn", "Reed"),
        new ProgramChange(70, "Bassoon", "Reed"),
        new ProgramChange(71, "Clarinet", "Reed"),
        new ProgramChange(72, "Piccolo", ""),
        new ProgramChange(73, "Flute", "Pipe"),
        new ProgramChange(74, "Recorder", "Pipe"),
        new ProgramChange(75, "Pan flute", "Pipe"),
        new ProgramChange(76, "Bottle blow / blown bottle", "Pipe"),
        new ProgramChange(77, "Shakuhachi", "Pipe"),
        new ProgramChange(78, "Whistle", "Pipe"),
        new ProgramChange(79, "Ocarina", "Pipe"),
        new ProgramChange(80, "Synth square wave", "Synth lead"),
        new ProgramChange(81, "Synth saw wave", "Synth lead"),
        new ProgramChange(82, "Synth calliope", "Synth lead"),
        new ProgramChange(83, "Synth chiff", "Synth lead"),
        new ProgramChange(84, "Synth charang", "Synth lead"),
        new ProgramChange(85, "Synth voice", "Synth lead"),
        new ProgramChange(86, "Synth fifths saw", "Synth lead"),
        new ProgramChange(87, "Synth brass and lead", "Synth lead"),
        new ProgramChange(88, "Fantasia / new age", "Synth pad"),
        new ProgramChange(89, "Warm pad", "Synth pad"),
        new ProgramChange(90, "Polysynth", "Synth pad"),
        new ProgramChange(91, "Space vox / choir", "Synth pad"),
        new ProgramChange(92, "Bowed glass", "Synth pad"),
        new ProgramChange(93, "Metal pad", "Synth pad"),
        new ProgramChange(94, "Halo pad", "Synth pad"),
        new ProgramChange(95, "Sweep pad", "Synth pad"),
        new ProgramChange(96, "Ice rain", "Synth effects"),
        new ProgramChange(97, "Soundtrack", "Synth effects"),
        new ProgramChange(98, "Crystal", "Synth effects"),
        new ProgramChange(99, "Atmosphere", "Synth effects"),
        new ProgramChange(100, "Brightness", "Synth effects"),
        new ProgramChange(101, "Goblins", "Synth effects"),
        new ProgramChange(102, "Echo drops / echoes", "Synth effects"),
        new ProgramChange(103, "Sci fi", "Synth effects"),
        new ProgramChange(104, "Sitar", "Ethnic"),
        new ProgramChange(105, "Banjo", "Ethnic"),
        new ProgramChange(106, "Shamisen", "Ethnic"),
        new ProgramChange(107, "Koto", "Ethnic"),
        new ProgramChange(108, "Kalimba", "Ethnic"),
        new ProgramChange(109, "Bag pipe", "Ethnic"),
        new ProgramChange(110, "Fiddle", "Ethnic"),
        new ProgramChange(111, "Shanai", "Ethnic"),
        new ProgramChange(112, "Tinkle bell", "Percussive"),
        new ProgramChange(113, "Agogo", "Percussive"),
        new ProgramChange(114, "Steel drums", "Percussive"),
        new ProgramChange(115, "Woodblock", "Percussive"),
        new ProgramChange(116, "Taiko drum", "Percussive"),
        new ProgramChange(117, "Melodic tom", "Percussive"),
        new ProgramChange(118, "Synth drum", "Percussive"),
        new ProgramChange(119, "Reverse cymbal", "Percussive"),
        new ProgramChange(120, "Guitar fret noise", "Sound effects"),
        new ProgramChange(121, "Breath noise", "Sound effects"),
        new ProgramChange(122, "Seashore", "Sound effects"),
        new ProgramChange(123, "Bird tweet", "Sound effects"),
        new ProgramChange(124, "Telephone ring", "Sound effects"),
        new ProgramChange(125, "Helicopter", "Sound effects"),
        new ProgramChange(126, "Applause", "Sound effects"),
        new ProgramChange(127, "Gunshot", "Sound effects"),
        new ProgramChange(128, "Percussion", "Percussion")
    ];

    static percussionProgramChange: ProgramChange[] = [
        new ProgramChange(128, "Acoustic bass drum", "Percussion", 35, "B"),
        new ProgramChange(128, "Bass drum 1", "Percussion", 36, "C"),
        new ProgramChange(128, "Side stick", "Percussion", 37, "C#/Db"),
        new ProgramChange(128, "Acoustic snare", "Percussion", 38, "D"),
        new ProgramChange(128, "Hand clap", "Percussion", 39, "D#/Eb"),
        new ProgramChange(128, "Electric snare", "Percussion", 40, "E"),
        new ProgramChange(128, "Low floor tom", "Percussion", 41, "F"),
        new ProgramChange(128, "Closed hihat", "Percussion", 42, "F#/Gb"),
        new ProgramChange(128, "High floor tom", "Percussion", 43, "G"),
        new ProgramChange(128, "Pedal hihat", "Percussion", 44, "G#/Ab"),
        new ProgramChange(128, "Low tom", "Percussion", 45, "A"),
        new ProgramChange(128, "Open hihat", "Percussion", 46, "A#/Bb"),
        new ProgramChange(128, "Low-mid tom", "Percussion", 47, "B"),
        new ProgramChange(128, "High-mid tom", "Percussion", 48, "C"),
        new ProgramChange(128, "Crash cymbal 1", "Percussion", 49, "C#/Db"),
        new ProgramChange(128, "High tom", "Percussion", 50, "D"),
        new ProgramChange(128, "Ride cymbal 1", "Percussion", 51, "D#/Eb"),
        new ProgramChange(128, "Chinese cymbal", "Percussion", 52, "E"),
        new ProgramChange(128, "Ride bell", "Percussion", 53, "F"),
        new ProgramChange(128, "Tambourine", "Percussion", 54, "F#/Gb"),
        new ProgramChange(128, "Splash cymbal", "Percussion", 55, "G"),
        new ProgramChange(128, "Cowbell", "Percussion", 56, "G#/Ab"),
        new ProgramChange(128, "Crash cymbal 2", "Percussion", 57, "A"),
        new ProgramChange(128, "Vibraslap", "Percussion", 58, "A#/Bb"),
        new ProgramChange(128, "Ride cymbal 2", "Percussion", 59, "B"),
        new ProgramChange(128, "High bongo", "Percussion", 60, "C"),
        new ProgramChange(128, "Low bongo", "Percussion", 61, "C#/Db"),
        new ProgramChange(128, "Mute high conga", "Percussion", 62, "D"),
        new ProgramChange(128, "Open high conga", "Percussion", 63, "D#/Eb"),
        new ProgramChange(128, "Low conga", "Percussion", 64, "E"),
        new ProgramChange(128, "High timbale", "Percussion", 65, "F"),
        new ProgramChange(128, "Low timbale", "Percussion", 66, "F#/Gb"),
        new ProgramChange(128, "High agogo", "Percussion", 67, "G"),
        new ProgramChange(128, "Low agogo", "Percussion", 68, "G#/Ab"),
        new ProgramChange(128, "Cabasa", "Percussion", 69, "A"),
        new ProgramChange(128, "Maracas", "Percussion", 70, "A#/Bb"),
        new ProgramChange(128, "Short whistle", "Percussion", 71, "B"),
        new ProgramChange(128, "Long whistle", "Percussion", 72, "C"),
        new ProgramChange(128, "Short guiro", "Percussion", 73, "C#/Db"),
        new ProgramChange(128, "Long guiro", "Percussion", 74, "D"),
        new ProgramChange(128, "Claves", "Percussion", 75, "D#/Eb"),
        new ProgramChange(128, "High wood block", "Percussion", 76, "E"),
        new ProgramChange(128, "Low wood block", "Percussion", 77, "F"),
        new ProgramChange(128, "Mute cuica", "Percussion", 78, "F#/Gb"),
        new ProgramChange(128, "Open cuica", "Percussion", 79, "G"),
        new ProgramChange(128, "Mute triangle", "Percussion", 80, "G#/Ab"),
        new ProgramChange(128, "Open triangle", "Percussion", 81, "A")
    ];

    static get(value: number): ProgramChange {
        return this.programChanges[value];
    }

    static percussion(value: number): ProgramChange {
        return this.percussionProgramChange[value - 35];
    }
}